# Generated by Django 5.1.2 on 2024-10-19 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('videoNumbers', models.IntegerField()),
                ('titleVideo', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('extension', models.CharField(max_length=100)),
                ('size', models.IntegerField()),
            ],
        ),
    ]
