# Generated by Django 5.1.2 on 2024-10-20 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProGolWatch', '0002_alter_fields_titlevideo_alter_fields_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fields',
            old_name='size',
            new_name='sizeMB',
        ),
    ]
