# Generated by Django 5.1.2 on 2024-10-20 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProGolWatch', '0003_rename_size_fields_sizemb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fields',
            name='sizeMB',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
